/**
 * Admin password verification.
 *
 * The password is never stored — only a PBKDF2-HMAC-SHA256 hash, in
 * `ADMIN_PASSWORD_HASH`, in the format:
 *
 *     pbkdf2.<iterations>.<base64 salt>.<base64 derived key>
 *
 * **Why `.` and not the conventional `$`.** Next.js parses `.env` through
 * dotenv-expand, which treats `$name` as a variable reference and substitutes
 * it. A `$`-separated hash is therefore silently mangled on load — the classic
 * `pbkdf2$210000$…` form arrives at the application with the `$210000` segment
 * expanded away, and every login fails with a "malformed hash" error that
 * points at the wrong thing. `.` is not part of the base64 alphabet
 * (A–Z a–z 0–9 + / =) and has no meaning to dotenv, so it separates
 * unambiguously.
 *
 * PBKDF2 is used instead of bcrypt/argon2 because it is available in Web Crypto
 * on every runtime this app can be deployed to, with no native module to
 * compile. Argon2id would be stronger per unit of CPU; for a single-operator
 * admin login behind rate limiting, 210k PBKDF2 iterations (the OWASP 2023
 * floor for SHA-256) is the right point on that curve.
 *
 * Generate a hash with: `npm run gen:password -- 'your password'`
 */

const PREFIX = 'pbkdf2';
const SEPARATOR = '.';
const DEFAULT_ITERATIONS = 210_000;
const KEY_LENGTH_BYTES = 32;
const SALT_LENGTH_BYTES = 16;

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(value: string): Uint8Array {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    'PBKDF2',
    false,
    ['deriveBits'],
  );

  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: salt as BufferSource, iterations, hash: 'SHA-256' },
    key,
    KEY_LENGTH_BYTES * 8,
  );

  return new Uint8Array(bits);
}

/** Produces the `ADMIN_PASSWORD_HASH` value for a plaintext password. */
export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_LENGTH_BYTES));
  const derived = await derive(password, salt, DEFAULT_ITERATIONS);
  return [PREFIX, DEFAULT_ITERATIONS, toBase64(salt), toBase64(derived)].join(SEPARATOR);
}

/**
 * Compares two byte arrays in time independent of where they first differ.
 * A naive `===` leaks the length of the matching prefix through timing, which
 * is enough to reconstruct a digest byte by byte.
 */
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= (a[i] as number) ^ (b[i] as number);
  return diff === 0;
}

/** Verifies a candidate password against `ADMIN_PASSWORD_HASH`. */
export async function verifyPassword(candidate: string): Promise<boolean> {
  const stored = process.env.ADMIN_PASSWORD_HASH;
  if (!stored) {
    console.error('[auth] ADMIN_PASSWORD_HASH is not set — admin login is disabled.');
    return false;
  }

  const parts = stored.split(SEPARATOR);
  if (parts.length !== 4 || parts[0] !== PREFIX) {
    console.error(
      '[auth] ADMIN_PASSWORD_HASH is malformed — expected pbkdf2.iterations.salt.key. ' +
        'If it contains "$", it was generated by an older version: regenerate with ' +
        "`npm run gen:password -- 'your password'`.",
    );
    return false;
  }

  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < 1000) {
    console.error('[auth] ADMIN_PASSWORD_HASH has an implausible iteration count.');
    return false;
  }

  try {
    const salt = fromBase64(parts[2] as string);
    const expected = fromBase64(parts[3] as string);
    const actual = await derive(candidate, salt, iterations);
    return timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

/** Constant-time username comparison, so a wrong user is not faster to detect. */
export function verifyUsername(candidate: string): boolean {
  const expected = process.env.ADMIN_USERNAME ?? 'admin';
  const encoder = new TextEncoder();
  return timingSafeEqual(encoder.encode(candidate), encoder.encode(expected));
}
